# Generated by Django 4.2.1 on 2023-05-30 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(default='', editable=False, max_length=7, unique=True)),
                ('amountPieces', models.IntegerField(default=0)),
                ('customerName', models.CharField(max_length=50, null=True)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('baseOrigin', models.CharField(default='CD de distribución ENEA PUDAHUEL', max_length=50)),
                ('receiverName', models.CharField(max_length=50, null=True)),
                ('receiveMail', models.CharField(blank=True, max_length=100, null=True)),
                ('receiverPhone', models.CharField(max_length=50, null=True)),
                ('receiverAddress', models.CharField(max_length=100, null=True)),
                ('receiverDistrict', models.CharField(max_length=50, null=True)),
                ('receiverCity', models.CharField(max_length=50, null=True)),
                ('receiverRegion', models.CharField(max_length=50, null=True)),
                ('locationName', models.CharField(default='', max_length=50)),
                ('patent', models.CharField(default='', max_length=10)),
                ('courierName', models.CharField(max_length=100, null=True)),
                ('receiver', models.CharField(max_length=50, null=True)),
                ('isDeliveryRetry', models.BooleanField(default=False)),
                ('estado_envio', models.CharField(choices=[('En Preparación', 'En Preparación'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado')], default='En Preparación', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='andesRestApi.envio')),
            ],
        ),
    ]
