# Generated by Django 4.2.1 on 2023-05-30 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('andesRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('En Reparto', 'En Reparto'), ('Entregado', 'Entregado')], max_length=20),
        ),
    ]
