# Generated by Django 4.2.1 on 2023-05-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andesRestApi', '0002_movimiento_fecha_hora_alter_movimiento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='envio',
        ),
        migrations.AddField(
            model_name='envio',
            name='movimientos',
            field=models.ManyToManyField(related_name='envios', to='andesRestApi.movimiento'),
        ),
    ]
