# Generated by Django 4.2.1 on 2023-05-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andesRestApi', '0003_remove_movimiento_envio_envio_movimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='movimientos',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='envio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='andesRestApi.envio'),
        ),
    ]
