# Generated by Django 4.2.1 on 2023-06-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andesRestApi', '0004_remove_envio_movimientos_movimiento_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='isDeliveryRetry',
        ),
    ]
